# Dan Vecellio

## Homework 03

### Due Tuesday, February 16th

In [140]:
import numpy as np
import time

### 1. Vector manipulation

Create a vector of zeros of size 10 but have the fifth value be 1.

In [141]:
arr1 = np.zeros(10)
arr1[4] = 1
arr1

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

### 2. Vector range

Create a vector with values ranging from 10 to 49, inclusive.

In [142]:
arr2 = np.arange(10,50)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3. Reverse a vector

Write a function, `reverse(x)` which reverses a vector, so that the first element becomes the last element. The API should be

    return a 1D vector with the elements reversed
    
    Input
    -----
        x: 1D array
    
    Output
    ------
        res: 1D array, with the elements of `x` reversed

Include this (or an equivalent description) in the function's docstring.

In [143]:
def reverse(x):
    '''return a 1D vector with the elements reversed

       Input - x: 1D array
       Output - res: 1D array, with the elements of `x` reversed'''
    res = []
    for a in range(len(x)-1,-1,-1):
        res = np.append(res, x[a])
    
        
    return res

In [144]:
arr3 = np.arange(4,12)
reverse(arr3)

array([ 11.,  10.,   9.,   8.,   7.,   6.,   5.,   4.])

### 4. Find indices of non-zero elements

Write a function `find_nonzero(x)` that finds the indices of non-zero elements, with an API like

    return the indices of non-zero elements of an array.

    Input:      x:  array
    Output:     indices: array of integer indices

Use the function to get out the non-zero elements from an array containing the elements [1,2,0,0,4,0].

In [145]:
def find_nonzero(x):
    '''return the indices of non-zero elements of an array.

        Input:      x:  array
        Output:     indices: array of integer indices'''
    
    indices = []
    for a in range(len(x)):
        if x[a] != 0:
            indices = np.append(indices, a)
        else:
            continue
            
    return indices

In [146]:
arr4 = np.array([1,2,0,0,4,0])
find_nonzero(arr4)

array([ 0.,  1.,  4.])

### 5. Array with random values

Create a 3x3x3 array with normally distributed ($\mu =0, \sigma=1)$ random values.

In [147]:
arr5 = np.random.normal(0,1,(3,3,3))
arr5

array([[[-0.51215698,  1.15331563, -1.07836103],
        [ 0.43836685,  0.43474861,  0.42902057],
        [-0.7674814 , -0.57061072, -0.29051025]],

       [[ 0.26420046, -1.07826664,  0.64595417],
        [ 0.22298757, -0.05568719,  0.01918507],
        [ 0.88939006,  0.51712943,  1.49660678]],

       [[ 1.57619822, -0.45898277, -0.78905183],
        [ 1.41119794,  0.57456456,  0.07804189],
        [-0.16278068,  0.31327876,  0.20625849]]])

### 6. Operations on an array with random values

Create a 10x10 array with random values. Find 
- the minimum value of the 2nd row
- the maximum value of the 4th column

In [148]:
arr6 = np.random.rand(10,10)
arr6_min = np.min(arr6[1,:])
arr6_max = np.max(arr6[:,3])

print arr6
print "The minimum value of the 2nd row is "+str(arr6_min)+''
print "The maximum value of the 4th column is "+str(arr6_max)+''

[[ 0.62052756  0.78036422  0.18845607  0.13001829  0.35749151  0.38922685
   0.94430334  0.2272608   0.37656844  0.17247208]
 [ 0.66628007  0.74244419  0.02369927  0.6825451   0.06089785  0.15833848
   0.55378226  0.90657025  0.11349438  0.52603183]
 [ 0.892566    0.35264494  0.45807118  0.42819073  0.59006122  0.04962296
   0.42975256  0.660596    0.29994001  0.14677581]
 [ 0.86973994  0.68923738  0.75885799  0.31992235  0.27324637  0.97304946
   0.14774655  0.27895172  0.2363715   0.74324752]
 [ 0.88146157  0.8546808   0.43012986  0.20197611  0.86843059  0.65919256
   0.8773421   0.6461318   0.01944698  0.32253794]
 [ 0.8126491   0.80318577  0.82301549  0.6052388   0.9916883   0.78487515
   0.89175996  0.36387538  0.32638996  0.66332313]
 [ 0.70843483  0.53321632  0.23852196  0.76030836  0.77178709  0.46064342
   0.13026655  0.7691428   0.68394656  0.01197937]
 [ 0.70092073  0.72814816  0.15170403  0.43893543  0.696162    0.23722425
   0.56565196  0.44900118  0.88485854  0.30629435]


### 7. Vector without end points

Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [149]:
arr7 = np.linspace(0,1,12)[1:-1]
arr7

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

### 8. Sorted random vector

Create a random vector of size 10, then sort it.

In [150]:
arr8 = np.sort(np.random.rand(10))
arr8

array([ 0.03463501,  0.12561147,  0.13209528,  0.17788522,  0.30259708,
        0.3756265 ,  0.59841872,  0.8566117 ,  0.90399545,  0.94538083])

### 9. Test for array equality

Write a function `is_equal(A, B)` that compare two arrays `A` and `B` and checks to see if they are equal. 

    return True if two arrays are the same shape and all the elements are equal.
    
    Inputs:
        A, B:  array
    Output:
        Bool:  True if A and B have the same shape and identical elements.

The arrays count as equal if they are the same shape and all elements in the array are equal.

In [151]:
def is_equal(A, B):
    '''return True if two arrays are the same shape and all the elements are equal.

    Inputs - A, B:  array
    Output - Bool:  True if A and B have the same shape and identical elements.'''
    
    if A.shape != B.shape:
        return False
    return bool(np.asarray(A == B).all())

In [152]:
arr9_1 = np.array([5,4,3])
arr9_2 = np.random.rand(5)
arr9_3 = arr9_2.copy()
is_equal(arr9_1,arr9_2)

False

### 10. Subtract the row mean from rows of a matrix

Create a matrix. Then subtract the mean of each row of the matrix from the respective row. Do this without using a loop (that is, using array operations).

In [153]:
arr10 = np.random.rand(4,5)
arr10_anom = arr10 - arr10.mean(axis=1)[:,np.newaxis]
print arr10.shape
print arr10.mean(axis=1)[:,np.newaxis].shape
print arr10_anom

(4, 5)
(4, 1)
[[-0.2800142   0.11926155  0.63297859 -0.29825315 -0.17397279]
 [-0.40552247  0.15520666  0.25566035  0.41897572 -0.42432026]
 [ 0.27314857  0.26322512 -0.09854138 -0.30014977 -0.13768254]
 [ 0.29332065 -0.45500018  0.17739832 -0.17624753  0.16052874]]


### 11. Multiply arrays

Multiply an array of dimension (5,5,3) with an array with dimensions (5,5). Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).

In [154]:
arr11_1 = np.random.rand(5,5,3)
arr11_2 = np.random.rand(5,5)
arr11_3 = np.random.rand(3,5,5)

ans11_1 = arr11_1 * arr11_2[:,:,np.newaxis]  #- This cannot be done
ans11_2 = arr11_3 * arr11_2

ans11_1, ans11_2

(array([[[  4.22660504e-01,   2.10034254e-01,   4.74708790e-01],
         [  4.49413682e-02,   2.99603862e-03,   1.96380058e-02],
         [  4.74469661e-01,   5.75928727e-01,   3.23684426e-01],
         [  3.34815624e-02,   4.81154292e-02,   1.81101769e-02],
         [  2.12347442e-01,   1.69381734e-01,   4.22693916e-02]],
 
        [[  7.43382491e-02,   7.78839593e-02,   2.84924449e-02],
         [  6.11984610e-02,   4.93715228e-02,   1.71416923e-01],
         [  1.38857251e-01,   3.56251891e-02,   1.17898029e-01],
         [  2.07032060e-02,   4.19257832e-02,   5.32560343e-02],
         [  3.69666663e-01,   1.58913363e-01,   2.09007547e-01]],
 
        [[  3.20015830e-01,   7.14638991e-01,   1.70691794e-01],
         [  1.57008552e-01,   6.75564390e-02,   2.88304243e-01],
         [  3.38657649e-01,   1.12659362e-01,   3.60191612e-01],
         [  2.60702201e-01,   2.68081701e-01,   6.22214907e-01],
         [  2.63790600e-01,   1.90563947e-01,   3.89560363e-01]],
 
        [[  3.20

### 12. Creating a new array

Starting with an array

    Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14].
    
Generate an array 

    R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]. 

In [155]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
R = []
for b in range(len(Z)):
    if b + 4 <= len(Z):
        R.append([Z[b:b+4]])
    else:
        break
    
print "R = ", R

R =  [[array([1, 2, 3, 4])], [array([2, 3, 4, 5])], [array([3, 4, 5, 6])], [array([4, 5, 6, 7])], [array([5, 6, 7, 8])], [array([6, 7, 8, 9])], [array([ 7,  8,  9, 10])], [array([ 8,  9, 10, 11])], [array([ 9, 10, 11, 12])], [array([10, 11, 12, 13])], [array([11, 12, 13, 14])]]


### 13. Convert from Cartesian to polar coordinates

Write a function `cart2polar(xy)` which takes in an Nx2 matrix of `x, y` pairs representing Cartesian coordinates and return the locations represented in polar coordinates in the same shape matrix. The API is

    Return equivalent polar coordinates of specified cartesian points.
    
    Inputs:
        xy: array
             Nx2 array of Cartesian coordinates, with columns x and y respectively.

    Returns:
        rp: array
            Nx2 array of polar coordinates, with columns radius and angle respectively


In [156]:
def cart2polar(xy):
    '''Return equivalent polar coordinates of specified cartesian points.

Inputs:
    xy: array
         Nx2 array of Cartesian coordinates, with columns x and y respectively.

Returns:
    rp: array
        Nx2 array of polar coordinates, with columns radius and angle respectively'''
    
    x, y = xy[:,0]*10,xy[:,1]*10
    r = np.vstack(np.sqrt(x**2+y**2))
    p = np.vstack(np.degrees(np.arctan2(y,x)))
    rp = np.concatenate([r,p],axis=1).reshape(10,2)
    
    return rp

In [157]:
xy = np.random.rand(10,2)
cart2polar(xy)

array([[ 10.10579426,  80.84241525],
       [  8.75880064,   7.23817022],
       [ 12.1848765 ,  42.32339342],
       [  4.09129196,  25.06317399],
       [  9.52160904,  12.79370383],
       [  5.59330501,  16.12695849],
       [  5.25792976,   2.49167995],
       [  9.41598815,  33.68035441],
       [  2.04116912,  88.73382976],
       [  2.93874303,  82.74831811]])

### 14. Compute and time for loops and array operations.

Calculate the time it takes to do what we did in class

    a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
    b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
    sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

and the time required for doing the same operation with a series of 4 `for` loops, one for each dimension of the arrays. Compare the times by calculating a ratio.

In [158]:
a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers

In [159]:
times_1 = time.time()
sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.
timee_1 = time.time()
time_1 = timee_1 - times_1
time_1

0.0013730525970458984

In [160]:
times_2 = time.time()
arr14 = np.empty_like(a)
for l in range(a.shape[0]):
    for k in range(a.shape[1]):
        for j in range(a.shape[2]):
            for i in range(a.shape[3]):
                arr14[l,k,j,i] = a[l,k,j,i]*b[l,k,j,i]

timee_2 = time.time()
time_2 = timee_2 - times_2
time_2

0.0036270618438720703

In [161]:
time_ratio = time_2/time_1
print "The loop function takes "+str(time_ratio)+" times longer than array broadcasting."

The loop function takes 2.64160444522 times longer than array broadcasting.


### 15. Fix the code

This code needs to be fixed so that it can run properly and pass the assertion test at the bottom. Write out what you changed to make it work and why it needed to be changed.

In [165]:
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    aa = aa/4.
    a[:2, :] -= aa

    return a*b[:,None]
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

print res

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

[[ 2.25  2.25]
 [ 2.25  2.25]
 [ 3.    3.  ]]


### Answers for Question 15

1. In return statement, added a second blank dimension to 'b' so that the array could be broadcast together.

2. Changed "aa /= 4." to "aa = aa/4" because before the first two rows of columns of a were being set to 0.25 as well as aa.

### 16. Calculate components of a vector

Read in file `data/burl1h2010.txt`. This file gives a bunch of data from a wind station. In particular, read in the wind direction, `WDIR`, and wind speed, `WSPD`. Then, write a function that calculates and returns the `u` and `v` components of this wind vector, which point along the x- and y-axes.

The function should have the following basic functionality:

    Take in vector and return components.
    
    Inputs:
        vdir: vector direction in degrees
        vspd: vector magnitude
        
    Returns:
        u: x component of vector
        v: y component of vector


In [166]:
def windcmpt(vdir,vspd):
    '''Take in wind vector and return components.

Inputs:
    vdir: vector direction in degrees
    vspd: vector magnitude

Returns:
    u: x component of vector
    v: y component of vector'''
    
    u = vspd*np.cos(vdir)
    v = vspd*np.sin(vdir)
    
    return u,v

In [167]:
data = np.genfromtxt('../python4geosciences/data/burl1h2010.txt')
wdir = data[:,5]
wspd = data[:,6]
windcmpt(wdir,wspd)

(array([-1.39148661, -3.19668806, -1.21206139, ..., -9.04175518,
         4.27262701,  7.13235823]),
 array([  2.65777445,  -1.65565257,  -3.06934964, ...,   6.94310185,
         11.10651423,  -7.29173958]))

### 17. (Grad) Write and use a class

Consider one of the data files located in `python4geosciences/data/MCH/`. Write a class, `dataclass`, to store some of the information in the file. The class should:

* be initialized with the name of the file (without file type suffix of .cnv2), and the temperature and salinity values found in the file;
* contain a method, `salt_mean`, which returns the mean of the salinity;
* contain a method, `temp_max`, which returns the maximum value of the temperature values.

Notice that there are many data files in this directory. It would be a lot of work to read them all in by hand. Instead, write a loop which loops through the file names, reads in the necessary data, calls `dataclass` to store the data in a class instance, and adds it to a list of all of the class instances. At the end of your solution, you should have a list of all of the class instances, one for each data file.

Hint: Check out the package `glob` for reading in file names with a wild card. 

In [168]:
import glob

In [169]:
class dataclass(object):
    
    def __init__(self,name,temp,salt):
        self.name = name
        self.temp = temp
        self.salt = salt
        
    def salt_mean(self):
        '''Find the mean of the salinity values.'''
        meansalt = np.mean(self.salt)
        
        return meansalt
        
    def temp_max(self):
        '''Find the maximum of the temperature values.'''
        maxtemp = np.max(self.temp)
        
        return maxtemp

ob = []    
filname = glob.glob('../python4geosciences/data/MCH/*')    
for m in filname:
    data = np.genfromtxt(m,skip_header=57,usecols=(2,5))
    name = m[31:-5]
    tem  = data[:,0]
    sal  = data[:,1]
    
    ob.append(dataclass(name,tem,sal))

In [170]:
ob[45].salt_mean()

35.207217999999997

### 18. (Grad) Running mean

Write a function that computes averages using a sliding window over a vector; that is, it should take in a vector and for every element in the vector, compute the average of that point with the N points on either side of the element. N should also be an input parameter, and the function should return the original vector if N=0. The returned vector should be the same size as the input vector.

Do not use the `pandas` package or the function `convolve`; instead, use a loop. Use the following API for your function:

    Return the running average of a vector, with averaging window of size N.
    
    Inputs:
        vec: Input vector
        N (int): Averaging window size, or number of elements to include in mean on either side of each element.
    
    Outputs:
        out: Vector of running-averaged values; same size as vec


In [171]:
def runmean(vec,N):
    '''Return the running average of a vector, with averaging window of size N.

Inputs:
    vec: Input vector
    N (int): Averaging window size, or number of elements to include in mean on either side of each element.
             If not enough values on either side, return unmodified value. if N = 0, return original vec.
Outputs:
    out: Vector of running-averaged values; same size as vec'''
    rmean = []
    for a in range(len(vec)):
        if N == 0:
            rmean = vec
        else: 
            if a < N:
                rmean = np.append(rmean,vec[a]) 
            elif a > len(vec)-N-1:
                rmean = np.append(rmean,vec[a])
            else:
                rmean = np.append(rmean,np.average(vec[a-N:a+N+1]))
    return rmean
        
            

In [172]:
arr18 = np.random.rand(20)*100
print arr18
runmean(arr18,2)

[ 98.37589756  42.81792428   0.88125494  39.56485424  40.9219669
  66.03681253   0.56373857  25.92993299   5.66155652   3.62402091
  29.40896712  46.44051825  91.79252156  19.18699214  22.52066443
  12.56483271  94.04681087  43.46749446  88.24658223  64.74203225]


array([ 98.37589756,  42.81792428,  44.51237958,  38.04456258,
        29.59372544,  34.60346105,  27.8228015 ,  20.3632123 ,
        13.03764322,  22.21299916,  35.38551687,  38.090604  ,
        41.8699327 ,  38.50110582,  48.02236434,  38.35735892,
        52.16927694,  60.61355051,  88.24658223,  64.74203225])