# Dan Vecellio

## Homework 03

### Due Tuesday, February 16th

In [2]:
import numpy as np
import time

### 1. Vector manipulation

Create a vector of zeros of size 10 but have the fifth value be 1.

In [76]:
arr1 = np.zeros(10)
arr1[4] = 1
arr1

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

### 2. Vector range

Create a vector with values ranging from 10 to 49, inclusive.

In [77]:
arr2 = np.arange(10,50)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3. Reverse a vector

Write a function, `reverse(x)` which reverses a vector, so that the first element becomes the last element. The API should be

    return a 1D vector with the elements reversed
    
    Input
    -----
        x: 1D array
    
    Output
    ------
        res: 1D array, with the elements of `x` reversed

Include this (or an equivalent description) in the function's docstring.

In [78]:
def reverse(x):
    '''return a 1D vector with the elements reversed

       Input - x: 1D array
       Output - res: 1D array, with the elements of `x` reversed'''
    res = []
    for a in range(len(x)-1,-1,-1):
        res = np.append(res, x[a])
    
        
    return res

In [79]:
arr3 = np.arange(4,12)
reverse(arr3)

array([ 11.,  10.,   9.,   8.,   7.,   6.,   5.,   4.])

### 4. Find indices of non-zero elements

Write a function `find_nonzero(x)` that finds the indices of non-zero elements, with an API like

    return the indices of non-zero elements of an array.

    Input:      x:  array
    Output:     indices: array of integer indices

Use the function to get out the non-zero elements from an array containing the elements [1,2,0,0,4,0].

In [80]:
def find_nonzero(x):
    '''return the indices of non-zero elements of an array.

        Input:      x:  array
        Output:     indices: array of integer indices'''
    
    indices = []
    for a in range(len(x)):
        if x[a] != 0:
            indices = np.append(indices, a)
        else:
            continue
            
    return indices

In [81]:
arr4 = np.array([1,2,0,0,4,0])
find_nonzero(arr4)

array([ 0.,  1.,  4.])

### 5. Array with random values

Create a 3x3x3 array with normally distributed ($\mu =0, \sigma=1)$ random values.

In [82]:
arr5 = np.random.normal(0,1,(3,3,3))
arr5

array([[[-0.09566371,  0.76465404,  0.13492145],
        [ 0.40913433,  0.50632004,  1.49856647],
        [ 1.11102049, -0.85905291, -0.19726508]],

       [[-2.38825331,  0.93708289,  0.52961973],
        [-1.19921956,  0.17090954, -0.96882051],
        [-0.40316661,  0.20455925,  0.26002054]],

       [[-0.89413285,  0.69046858, -0.5953708 ],
        [ 0.62169374,  0.67532408, -1.0955301 ],
        [ 0.4908666 ,  0.83690483,  0.70316257]]])

### 6. Operations on an array with random values

Create a 10x10 array with random values. Find 
- the minimum value of the 2nd row
- the maximum value of the 4th column

In [83]:
arr6 = np.random.rand(10,10)
arr6_min = np.min(arr6[1,:])
arr6_max = np.max(arr6[:,3])

print arr6
print "The minimum value of the 2nd row is "+str(arr6_min)+''
print "The maximum value of the 4th column is "+str(arr6_max)+''

[[ 0.98110246  0.11202623  0.8763749   0.47624748  0.52250724  0.59285406
   0.35258999  0.79282521  0.49720563  0.97994043]
 [ 0.31172286  0.08547764  0.47226915  0.33103671  0.10954964  0.93548864
   0.07406799  0.1471949   0.57469899  0.88477709]
 [ 0.22091562  0.02960199  0.28319703  0.24312945  0.9749858   0.66820752
   0.45776857  0.4098503   0.33205446  0.33105255]
 [ 0.34199802  0.33348452  0.36862941  0.45047636  0.60175064  0.87122286
   0.91683138  0.16419463  0.88231714  0.88164907]
 [ 0.41825292  0.79216407  0.13040276  0.44440577  0.82920173  0.42139573
   0.29138379  0.74401047  0.40679651  0.39232068]
 [ 0.11981494  0.32444841  0.72410924  0.15257528  0.08154008  0.83401974
   0.12143361  0.43369726  0.07017206  0.14215827]
 [ 0.74631     0.85471286  0.42427293  0.91513545  0.1146296   0.53676226
   0.63987467  0.78990376  0.41099994  0.21914043]
 [ 0.24880854  0.81078877  0.22409615  0.6591763   0.50958066  0.93557694
   0.20477264  0.39263458  0.44164913  0.7110555 ]


### 7. Vector without end points

Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [84]:
arr7 = np.linspace(0,1,12)[1:-1]
arr7

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

### 8. Sorted random vector

Create a random vector of size 10, then sort it.

In [85]:
arr8 = np.sort(np.random.rand(10))
arr8

array([ 0.03731024,  0.08553586,  0.47312818,  0.59286983,  0.62353047,
        0.66738605,  0.80311725,  0.84316032,  0.85108355,  0.97555293])

### 9. Test for array equality

Write a function `is_equal(A, B)` that compare two arrays `A` and `B` and checks to see if they are equal. 

    return True if two arrays are the same shape and all the elements are equal.
    
    Inputs:
        A, B:  array
    Output:
        Bool:  True if A and B have the same shape and identical elements.

The arrays count as equal if they are the same shape and all elements in the array are equal.

In [132]:
def is_equal(A, B):
    '''return True if two arrays are the same shape and all the elements are equal.

    Inputs - A, B:  array
    Output - Bool:  True if A and B have the same shape and identical elements.'''
    
    if A.shape != B.shape:
        return False
    return bool(np.asarray(A == B).all())

In [135]:
arr9_1 = np.array([5,4,3])
arr9_2 = np.random.rand(5)
arr9_3 = arr9_2.copy()
is_equal(arr9_1,arr9_2)

False

### 10. Subtract the row mean from rows of a matrix

Create a matrix. Then subtract the mean of each row of the matrix from the respective row. Do this without using a loop (that is, using array operations).

In [15]:
arr10 = np.random.rand(4,5)
arr10_anom = arr10 - arr10.mean(axis=1)[:,np.newaxis]
print arr10.shape
print arr10.mean(axis=1)[:,np.newaxis].shape
print arr10_anom

(4, 5)
(4, 1)
[[ 0.47249486 -0.40483921 -0.24449489 -0.2647217   0.44156094]
 [-0.16473562 -0.40154648  0.42261581 -0.07325589  0.21692218]
 [-0.43697195  0.25360043  0.25508569 -0.33468472  0.26297055]
 [ 0.43841684 -0.3363533   0.25602173 -0.10039166 -0.2576936 ]]


### 11. Multiply arrays

Multiply an array of dimension (5,5,3) with an array with dimensions (5,5). Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).

In [109]:
arr11_1 = np.random.rand(5,5,3)
arr11_2 = np.random.rand(5,5)
arr11_3 = np.random.rand(3,5,5)

ans11_1 = arr11_1 * arr11_2[:,:,np.newaxis]  #- This cannot be done
ans11_2 = arr11_3 * arr11_2

ans11_1, ans11_2

(array([[[ 0.08411471,  0.33056255,  0.25028535],
         [ 0.15405274,  0.09444573,  0.49371572],
         [ 0.64491637,  0.27621288,  0.79019703],
         [ 0.36406926,  0.24014763,  0.09988621],
         [ 0.20642114,  0.31646436,  0.53124633]],
 
        [[ 0.01377523,  0.23812637,  0.19442845],
         [ 0.63894488,  0.54486725,  0.42306204],
         [ 0.18996443,  0.19188635,  0.04086526],
         [ 0.17865891,  0.01329058,  0.2553166 ],
         [ 0.48076661,  0.40833895,  0.4148283 ]],
 
        [[ 0.07237804,  0.23229387,  0.12234457],
         [ 0.24233979,  0.36154717,  0.29055156],
         [ 0.67488392,  0.18321007,  0.29822695],
         [ 0.05720759,  0.42215954,  0.15561196],
         [ 0.03504397,  0.05810113,  0.02597068]],
 
        [[ 0.01602339,  0.11897982,  0.08950294],
         [ 0.00611831,  0.51221806,  0.29693042],
         [ 0.41234738,  0.55783678,  0.48656195],
         [ 0.58394592,  0.43001105,  0.27447353],
         [ 0.27467732,  0.02781386,  0.10

### 12. Creating a new array

Starting with an array

    Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14].
    
Generate an array 

    R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]. 

In [110]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
R = []
for b in range(len(Z)):
    if b + 4 <= len(Z):
        R.append([Z[b:b+4]])
    else:
        break
    
print "R = ", R

R =  [[array([1, 2, 3, 4])], [array([2, 3, 4, 5])], [array([3, 4, 5, 6])], [array([4, 5, 6, 7])], [array([5, 6, 7, 8])], [array([6, 7, 8, 9])], [array([ 7,  8,  9, 10])], [array([ 8,  9, 10, 11])], [array([ 9, 10, 11, 12])], [array([10, 11, 12, 13])], [array([11, 12, 13, 14])]]


### 13. Convert from Cartesian to polar coordinates

Write a function `cart2polar(xy)` which takes in an Nx2 matrix of `x, y` pairs representing Cartesian coordinates and return the locations represented in polar coordinates in the same shape matrix. The API is

    Return equivalent polar coordinates of specified cartesian points.
    
    Inputs:
        xy: array
             Nx2 array of Cartesian coordinates, with columns x and y respectively.

    Returns:
        rp: array
            Nx2 array of polar coordinates, with columns radius and angle respectively


In [113]:
def cart2polar(xy):
    '''Return equivalent polar coordinates of specified cartesian points.

Inputs:
    xy: array
         Nx2 array of Cartesian coordinates, with columns x and y respectively.

Returns:
    rp: array
        Nx2 array of polar coordinates, with columns radius and angle respectively'''
    
    x, y = xy[:,0]*10,xy[:,1]*10
    r = np.vstack(np.sqrt(x**2+y**2))
    p = np.vstack(np.degrees(np.arctan2(y,x)))
    rp = np.concatenate([r,p],axis=1).reshape(10,2)
    
    return rp

In [114]:
xy = np.random.rand(10,2)
cart2polar(xy)

array([[  8.23143272,  77.55909367],
       [  2.54697082,  30.04507106],
       [  6.42594651,  81.38881925],
       [  6.64112818,  20.26471703],
       [ 11.77789421,  33.82923918],
       [  7.91671579,  87.19706916],
       [ 10.55735614,  69.55366194],
       [ 12.76628215,  45.62308452],
       [  5.0653869 ,   1.36609271],
       [ 11.61147337,  41.07584234]])

### 14. Compute and time for loops and array operations.

Calculate the time it takes to do what we did in class

    a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
    b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
    sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

and the time required for doing the same operation with a series of 4 `for` loops, one for each dimension of the arrays. Compare the times by calculating a ratio.

In [115]:
a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers

In [116]:
times_1 = time.time()
sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.
timee_1 = time.time()
time_1 = timee_1 - times_1
time_1

0.0002200603485107422

In [117]:
times_2 = time.time()
arr14 = np.empty_like(a)
for l in range(a.shape[0]):
    for k in range(a.shape[1]):
        for j in range(a.shape[2]):
            for i in range(a.shape[3]):
                arr14[l,k,j,i] = a[l,k,j,i]*b[l,k,j,i]

timee_2 = time.time()
time_2 = timee_2 - times_2
time_2

0.0030231475830078125

In [118]:
time_ratio = time_2/time_1
print "The loop function takes "+str(time_ratio)+" times longer than array broadcasting."

The loop function takes 13.7378114843 times longer than array broadcasting.


### 15. Fix the code

This code needs to be fixed so that it can run properly and pass the assertion test at the bottom. Write out what you changed to make it work and why it needed to be changed.

In [119]:
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    print aa
    aa = aa/4.
    print aa
    print a
    a[:2, :] -= aa
    print a

    return a*b[:,None]
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

res

#assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

[[ 1.  1.]
 [ 1.  1.]]
[[ 0.25  0.25]
 [ 0.25  0.25]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 0.75  0.75]
 [ 0.75  0.75]
 [ 1.    1.  ]]


array([[ 2.25,  2.25],
       [ 2.25,  2.25],
       [ 3.  ,  3.  ]])

### Answers for Question 15

1. In return statement, added a second blank dimension to 'b' so that the array could be broadcast together.

2. Changed "aa /= 4." to "aa = aa/4" because before the first two rows of columns of a were being set to 0.25 as well as aa.

### 16. Calculate components of a vector

Read in file `data/burl1h2010.txt`. This file gives a bunch of data from a wind station. In particular, read in the wind direction, `WDIR`, and wind speed, `WSPD`. Then, write a function that calculates and returns the `u` and `v` components of this wind vector, which point along the x- and y-axes.

The function should have the following basic functionality:

    Take in vector and return components.
    
    Inputs:
        vdir: vector direction in degrees
        vspd: vector magnitude
        
    Returns:
        u: x component of vector
        v: y component of vector


In [120]:
def windcmpt(vdir,vspd):
    '''Take in wind vector and return components.

Inputs:
    vdir: vector direction in degrees
    vspd: vector magnitude

Returns:
    u: x component of vector
    v: y component of vector'''
    
    u = vspd*np.cos(vdir)
    v = vspd*np.sin(vdir)
    
    return u,v

In [121]:
data = np.genfromtxt('../python4geosciences/data/burl1h2010.txt')
wdir = data[:,5]
wspd = data[:,6]
windcmpt(wdir,wspd)

(array([-1.39148661, -3.19668806, -1.21206139, ..., -9.04175518,
         4.27262701,  7.13235823]),
 array([  2.65777445,  -1.65565257,  -3.06934964, ...,   6.94310185,
         11.10651423,  -7.29173958]))

### 17. (Grad) Write and use a class

Consider one of the data files located in `python4geosciences/data/MCH/`. Write a class, `dataclass`, to store some of the information in the file. The class should:

* be initialized with the name of the file (without file type suffix of .cnv2), and the temperature and salinity values found in the file;
* contain a method, `salt_mean`, which returns the mean of the salinity;
* contain a method, `temp_max`, which returns the maximum value of the temperature values.

Notice that there are many data files in this directory. It would be a lot of work to read them all in by hand. Instead, write a loop which loops through the file names, reads in the necessary data, calls `dataclass` to store the data in a class instance, and adds it to a list of all of the class instances. At the end of your solution, you should have a list of all of the class instances, one for each data file.

Hint: Check out the package `glob` for reading in file names with a wild card. 

In [122]:
import glob

In [123]:
class dataclass(object):
    
    def __init__(self,name,temp,salt):
        self.name = name
        self.temp = temp
        self.salt = salt
        
    def salt_mean(self):
        '''Find the mean of the salinity values.'''
        meansalt = np.mean(self.salt)
        
        return meansalt
        
    def temp_max(self):
        '''Find the maximum of the temperature values.'''
        maxtemp = np.max(self.temp)
        
        return maxtemp

ob = []    
filname = glob.glob('../python4geosciences/data/MCH/*')    
for m in filname:
    data = np.genfromtxt(m,skip_header=57,usecols=(2,5))
    name = m[31:-5]
    tem  = data[:,0]
    sal  = data[:,1]
    
    ob.append(dataclass(name,tem,sal))

In [124]:
ob[45].name

'm1017c'

### 18. (Grad) Running mean

Write a function that computes averages using a sliding window over a vector; that is, it should take in a vector and for every element in the vector, compute the average of that point with the N points on either side of the element. N should also be an input parameter, and the function should return the original vector if N=0. The returned vector should be the same size as the input vector.

Do not use the `pandas` package or the function `convolve`; instead, use a loop. Use the following API for your function:

    Return the running average of a vector, with averaging window of size N.
    
    Inputs:
        vec: Input vector
        N (int): Averaging window size, or number of elements to include in mean on either side of each element.
    
    Outputs:
        out: Vector of running-averaged values; same size as vec


In [125]:
def runmean(vec,N):
    '''Return the running average of a vector, with averaging window of size N.

Inputs:
    vec: Input vector
    N (int): Averaging window size, or number of elements to include in mean on either side of each element.
             If not enough values on either side, return unmodified value. if N = 0, return original vec.
Outputs:
    out: Vector of running-averaged values; same size as vec'''
    rmean = []
    for a in range(len(vec)):
        if N == 0:
            rmean = vec
        else: 
            if a < N:
                rmean = np.append(rmean,vec[a]) 
            elif a > len(vec)-N-1:
                rmean = np.append(rmean,vec[a])
            else:
                rmean = np.append(rmean,np.average(vec[a-N:a+N+1]))
    return rmean
        
            

In [126]:
arr18 = np.random.rand(20)*100
print arr18
runmean(arr18,2)

[ 57.82805969  65.28973648  21.07878342  24.20454475  29.4415283
  46.80325395  28.32661573  19.94498898  12.17365718  72.33452382
  21.1631184   19.87698143   9.50204675  90.44498532  85.73018333
  13.21211716  54.06544059  88.35311071  47.99472988   3.56234744]


array([ 57.82805969,  65.28973648,  39.56853053,  37.36356938,
        29.97094523,  29.74418634,  27.33800883,  35.91660793,
        30.78858082,  29.09865396,  27.01006552,  42.66433114,
        45.34346304,  43.7532628 ,  50.59095463,  66.36116742,
        57.87111633,  41.43754916,  47.99472988,   3.56234744])